apiVersion: v1
kind: Service
metadata: 
  # labels:
  #   app: flask
  name: flask-svc
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
