name: test

on:
  push:
    branches: gh-pages
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish helm chart
        uses: ./
        with:
#           token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: test-chart
          access-token: ${{ secrets.ACCESS_TOKEN }}
