name: release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: anikpujan/helm-chart@main
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
